work-directory: "WORK-DIRECTORY"
input-directory: "/home/user/pingu/no-inputs"
timeout: 10s
target-port: 4567
jail-uid: UID
jail-gid: GID
seed: 0
target: msquic
svf-so-path: "/home/user/pingu/target/release/libsvf_sys.so"

monitor:
  url: "MONITOR-URL"
  org: "MONITOR-ORG"
  bucket: "MONITOR-BUCKET"
  token: "MONITOR-TOKEN"
  http-proxy: "HTTP-PROXY"

source:
  bin-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/quicsample"
  root-path: "/home/user/target/pingu/generator/msquic"
  env:
    - LD_LIBRARY_PATH: "/home/user/pingu/target/debug:/home/user/pingu/target/release"
    - FAKE_RANDOM: "1"
    - FAKE_TIME: "2026-02-01 12:00:00"
    - ASAN_OPTIONS: "detect_leaks=0:disable_coredump=0:abort_on_error=1:print_stacktrace=1:symbolize=1:log_path=/home/user/pingu/tmp/fuzzing-output/0/source/state"
  arguments: ["-client", "-unsecure", "-target:127.0.0.1"]
  cwd: "/home/user/target/pingu/generator/msquic"
  compdb-path: "/home/user/target/pingu/generator/msquic/build/compile_commands.json"
  pp-json-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/quicsample.bc.pingu.pp.json"
  ppmeta-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/quicsample.bc.pingu.ppmeta.ll"
  extapi-path: "/home/user/pingu/pingu-agent/pass/build/extapi.bc"
  svfg-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/svfg.dot"
  icfg-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/icfg.dot"
  cg-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/cg.dot"
  func-block-table-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/function_block_table.json"
  func-table-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/function_table.json"
  loop-info-path: "/home/user/target/pingu/generator/msquic/build/bin/Release/loops.pingu.json"
  log-stdout: true
  log-stderr: true
  log-level: info

sink:
  bin-path: "/home/user/target/pingu/consumer/msquic/build/bin/Release/quicsample"
  root-path: "/home/user/target/pingu/consumer/msquic"
  env:
    - LD_LIBRARY_PATH: "/home/user/pingu/target/debug:/home/user/pingu/target/release"
    - FAKE_RANDOM: "1"
    - FAKE_TIME: "2026-02-01 12:00:00"
    - ASAN_OPTIONS: "disable_coredump=0:abort_on_error=1:symbolize=1:detect_leaks=0:handle_abort=0:handle_segv=2:handle_sigbus=2:handle_sigill=2:detect_stack_use_after_return=0:detect_odr_violation=0:log_path=/home/user/pingu/tmp/fuzzing-output/0/sink/state"
  arguments:
    [
      "-server",
      "-cert_file:/home/user/profuzzbench/cert/fullchain.crt",
      "-key_file:/home/user/profuzzbench/cert/server.key",
      "-listen:0.0.0.0",
      "-port:4567"
    ]
  cwd: "/home/user/target/pingu/consumer/msquic"
  compdb-path: "/home/user/target/pingu/consumer/msquic/build/compile_commands.json"
  pp-json-path: "/home/user/target/pingu/consumer/msquic/build/bin/Release/quicsample.bc.pingu.pp.json"
  ppmeta-path: "/home/user/target/pingu/consumer/msquic/build/bin/Release/quicsample.bc.pingu.ppmeta.ll"
  extapi-path: "/home/user/pingu/pingu-agent/pass/build/extapi.bc"
  svfg-path: "/home/user/target/pingu/consumer/msquic/build/bin/Release/svfg.dot"
  icfg-path: "/home/user/target/pingu/consumer/msquic/build/bin/Release/icfg.dot"
  cg-path: "/home/user/target/pingu/consumer/msquic/build/bin/Release/cg.dot"
  loop-info-path: "/home/user/target/pingu/consumer/msquic/build/bin/Release/loops.pingu.json"
  func-block-table-path: "/home/user/target/pingu/consumer/msquic/build/bin/Release/function_block_table.json"
  log-stdout: true
  log-stderr: true
  log-level: info
  allow-unstable-sink: true

stages:
  deterministic:
    enable: true
    timeout-streak-threshold: 3
    source-signaled-streak-threshold: 3
    max-consecutive-not-interesting-per-pp: 64
  target-state:
    pp-reachability-routing:
      threshold: 0.1
      enable: false
      lambda: 0.1
    probabilistic:
      llm: 0.4
    sink-cmplog:
      enable: true
    source-block:
      enable: true

gcov:
  reporter: "gcovr"
  timeout: 5s
  bin-path: "/home/user/profuzzbench/target/gcov/msquic/build/bin/Release/quicsample"
  env:
    - LD_PRELOAD: "/home/user/libfake_random.so:/home/user/libgcov_preload.so"
    - FAKE_RANDOM: "1"
    - FAKE_TIME: "2026-02-01 12:00:00"
  src-dir: "/home/user/profuzzbench/target/gcov/msquic"

svf:
  llvm-path: "/usr"
  svf-path: "/home/user/SVF"
  z3-path: "/home/user/SVF/z3.obj"
  build-mode: "Release"

solver:
  clangd-path: "/home/user/.serena/language_servers/static/ClangdLanguageServer/clangd/clangd_19.1.2/bin/clangd"
  extract-snippet-path: "/home/user/pingu/pingu-solver/tools/build/extract-snippet"
  sut: "msquic"
  protocol: "quic"
  max-solution-candidates: 3
  solver-cwd: "/home/user/pingu/pingu-solver"
  py-path: "/home/user/pingu/.venv/bin/python3"
  solver-py-path: "/home/user/pingu/pingu-solver/src/solver.py"
  llm:
    max-rounds: 10
    parallel-sessions: 2
    timeout: 300s
    openai-model: "gpt-5.4"
    openai-api-base-url: "OPENAI-API-BASE-URL"
    openai-use-responses-api: false
    http-proxy: "HTTP-PROXY"
    seed: 123
    env:
      - LANGSMITH_TRACING: false
      - LANGSMITH_ENDPOINT: https://api.smith.langchain.com
      - LANGSMITH_PROJECT: pingu-solver

scheduler:
  katz-centrality:
    enable: true
    alpha: 0.001
    max-iter: 1000
